#11 - integrate design system's variables with tailwindcss
forjadev/mjo-forja-webpage pull request #12
Opened 2023-07-31 20:34 UTC by junio12o

Also did some changes that include:
- remove `package-lock.json` generated from npm build process and update `.gitignore` :octocat:
- include yarn lock file :yarn:

Fonts are being sourced on [app/page.tsx](./src/app/page.tsx)

2023-07-31 21:17 UTC, kevinCubas requested changes

2023-07-31 21:17 UTC, kevinCubas commented on src/app/page.tsx
The config looks perfect, great job!

I just have a minor suggestion: Instead of importing and defining fonts in the individual `page` file, consider importing them in the `Layout` file. This way, the fonts will be available for all future pages.

Does it make sense to you? Let me know your thoughts, happy code 💜🚀

2023-08-01 22:31 UTC, junio12o commented on src/app/page.tsx
Great point!

2023-08-01 22:54 UTC, kevinCubas approved these changes

2023-08-01 22:55 UTC, arthur404dev approved these changes
LGTM

2023-08-01 22:56 UTC, merged