Feature/mjo 5
forjadev/mjo-forja-webpage pull request #15
Opened 2023-08-07 20:41 UTC by rodrigosantosdev

we create the navigation component we use semantic HTML tags, we add tailwind and stories variables

2023-08-07 20:52 UTC, MBrunoS requested changes
Please add the `ref` prop in the NavItem component

2023-08-08 13:21 UTC, MBrunoS approved these changes
Ok!

2023-08-10 00:18 UTC, Wtheodoro reviewed
lgtm

2023-08-10 00:18 UTC, Wtheodoro commented on src/components/Navbar/Navbar.tsx
> +            key={item.href}
As each item from navigation will have different href, you can add a TODO comment before const declaration. Just a suggestion.

2023-08-30 21:52 UTC, MBrunoS approved these changes
Great

2023-08-30 21:52 UTC, MBrunoS commented on src/components/Navbar/Navbar.tsx
> +    <NavigationMenu.Root className="px-4 py-4 border border-metal-light rounded-full bg-surface-secondary-light/80 dark:bg-surface-secondary/50 shadow-lg shadow-[#45A6AA]/5">
I noticed that the background needs to be changed, because the design was updated.

2023-08-30 21:52 UTC, MBrunoS commented on src/components/Navbar/NavIgationPrimitives.tsx
It's just a detail, but the filename is with a upper "i" (NavIgation)

2023-08-30 23:38 UTC, kevinCubas commented on src/components/Navbar/NavIgationPrimitives.tsx
Didn't even noticed it, thanks. I've already renamed it

2023-09-16 12:38 UTC, Wtheodoro approved these changes

2024-03-22 18:17 UTC, merged